### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by ritikraj0315** [syncloudsoftech/taktak#1]
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: C:\Users\rriti\AppData\Local\Android\Sdk\platforms\android-33\android.jar.
Cannot create mockable android.jar
C:\Users\rriti\AppData\Local\Android\Sdk\platforms\android-33\android.jar

![Screenshot (218)](https://user-images.githubusercontent.com/97241218/203396097-99469848-7905-4f3f-9a65-666e7724a2f0.png)

**Comment by vaibhavpandeyvpz** [comment]
Updating your build tools should help.
